name: native_platform
description: Nyrna's package to interactive with the native platform.
version: 1.0.0
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.3
  win32: ^2.2.5
  win32_suspend_process: ^1.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
