name: Build Win32
on:
  workflow_dispatch:
  pull_request:
  release:
    types:
      - created
jobs:
  build_and_preview:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64
      - name: Populate version environment variable
        run: |
          choco install yq
          $VER = yq e .version pubspec.yaml
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Install AutoHotkey
        run: choco install autohotkey
      - name: Add AutoHotkey to path
        run: echo "C:\Program Files\AutoHotkey\Compiler" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Build Nyrna portable
        run: |
          flutter config --enable-windows-desktop
          flutter pub get
          flutter build windows

          move build\windows\runner\Release build\Nyrna

          xcopy C:\Windows\System32\msvcp140.dll build\Nyrna
          xcopy C:\Windows\System32\vcruntime140.dll build\Nyrna
          xcopy C:\Windows\System32\vcruntime140_1.dll build\Nyrna

          cd .\packages\active_window
          dart pub get
          dart compile exe .\bin\toggle_active_window.dart
          editbin.exe /subsystem:windows .\bin\toggle_active_window.exe
          xcopy .\bin\toggle_active_window.exe ..\..\build\Nyrna
          
          Ahk2Exe.exe /in .\hotkey\toggle_active_hotkey.ahk /out ..\..\build\Nyrna\toggle_active_hotkey.exe
          cd ..\..
      - name: Package with Inno Setup
        run: |
          iscc /dMyAppVersion=${{ env.VERSION }} packaging\win32\inno_setup_script.iss
      - name: Add PORTABLE file
        run: New-Item -Path .\build\Nyrna\ -Name "PORTABLE" -ItemType "file"
      - uses: actions/upload-artifact@v2
        with:
          name: nyrna-windows-portable
          path: build\Nyrna
      - uses: actions/upload-artifact@v2
        with:
          name: nyrna-windows-installer
          path: build\nyrna-windows-installer.exe
