name: Build Linux AppImage
on:
  workflow_dispatch:
  push:
  pull_request:
  release:
    types:
      - created
jobs:
  build-appimage:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: beta
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libblkid-dev zsync
      - name: Set environment variables
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Flutter setup
        run: |
          flutter channel beta
          flutter config --enable-linux-desktop
          flutter upgrade
      - name: Build Flutter app
        run: |
          flutter pub get
          flutter build linux
      - name: Build AppImage
        uses: docker://appimagecrafters/appimage-builder:0.8.5
        env:
          APP_VERSION: ${{ env.VERSION }}
        with:
          entrypoint: appimage-builder
          args: --recipe packaging/linux/appimage/AppImageBuilder.yml --skip-test
      - uses: actions/upload-artifact@v2
        with:
          name: Nyrna-AppImage
          path: |
            *.AppImage
            *.zsync
